{
    "0": "Butterfly Sign \"Minute Scales\"",
    "2": "Butterfly Sign \"Swallowtail's Scales\"",
    "4": "Butterfly Sign \"Fluttering Summer\"",
    "6": "Butterfly Sign \"Midsummer Wingbeats\"",
    "8": "Rain Sign \"Captive Autumn Rain\"",
    "10": "Rain Sign \"Cursed Torrential Rain\"",
    "12": "Blade Sign \"Yamanba's Kitchen Knife Sharpening\"",
    "14": "Blade Sign \"Yamanba's Oni Kitchen Knife Sharpening\"",
    "16": "Exhaust Sign \"Mountain Murder\"",
    "18": "Exhaust Sign \"Bloody Mountain Murder\"",
    "20": "Spring Sign \"Surprise Spring\"",
    "22": "Dog Sign \"Stray Dog's Walk\"",
    "24": "Hound Sign \"Mountain Hound's Walk\"",
    "26": "Spinning Top \"Koma-Inu Spin\"",
    "29": "Spinning Top \"Curl Up and Die\"",
    "30": "Koma Sign \"Solitary A-Um Breathing\"",
    "34": "Magic Sign \"Instant Bohdi\"",
    "38": "Magic Sign \"Bullet Golem\"",
    "42": "Jizo \"Criminal Salvation\"",
    "46": "Bamboo Sign \"Bamboo Spear Dance\"",
    "48": "Bamboo Sign \"Bamboo Crazy Dance\"",
    "50": "Myoga \"Forget Your Name\"",
    "54": "Sasa Sign \"Tanabata Star Festival\"",
    "62": "Dance Sign \"Behind Festival\"",
    "58": "Myoga \"Behind You\"",
    "66": "Mad Dance \"Tengu-odoshi\"",
    "118": "\"Anarchy Bullet Hell\"",
    "109": "Secret Ceremony \"Reverse Invoker\"",
    "115": "Secret Ceremony \"Sword of Seven Stars\"",
    "106": "Drum Dance \"Powerful Cheers\"",
    "107": "Mad Dance \"Crazy Back Dance\"",
    "108": "Bullet Dance \"Second Typhoon\"",
    "74": "Summer \"Scorch By Hot Summer\"",
    "78": "Autumn \"Die of Famine\"",
    "82": "Winter \"Black Snowman\"",
    "86": "Spring \"April Wizard\"",
    "90": "\"Breezy Cherry Blossom\"",
    "94": "\"Perfect Summer Ice\"",
    "98": "\"Crazy Fall Wind\"",
    "102": "\"Extreme Winter\"",
    "113": "Secret Ceremony \"Mad Words of the Backdoor\"",
    "114": "Secret Ceremony \"Mataradukka\"",
    "116": "Secret Ceremony \"Incapable Performer\"",
    "111": "Secret Ceremony \"Dupion Barrage\"",
    "36": "Magic Sign \"Instant Bodai\"",
    "44": "Jizo \"Hellfire Salvation\"",
    "117": "\"The Back's Dark Sarugaku\"",
    "70": "Back Sign \"Secret God's Halo\"",
    "73": "Back Sign \"Absolute Secret God's Halo\"",
    "84": "Winter \"Snowman of Abormal Snowfall\"",
    "76": "Summer \"Scorched Earth of Abnormal Heat\"",
    "80": "Autumn \"Preta of Abnormal Withering\"",
    "88": "Spring \"Magic of Abnormal Fallen Flowers\"",
    "40": "Magic Sign \"Gigantic Bullet Pet Golem\"",
    "68": "Mad Dance \"Fearsome Tengu Frenzy\"",
    "110": "Secret Ceremony \"Shot in the Back\"",
    "112": "Secret Ceremony \"Flames of Impurity\""
}